[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[project]
name = "agent-inspector"
dynamic = ["version"]
description = "CLI launcher for Cylestio Perimeter with default OpenAI and Anthropic configs"
readme = "README.md"
license = "MIT"
authors = [
    {name = "Cylestio"}
]
requires-python = ">=3.9"
dependencies = [
    "typer[all]>=0.12.3",
    "pyyaml>=6.0.1",
    "cylestio-perimeter>=1.3.3",
]

[project.scripts]
agent-inspector = "agent_inspector.cli:main"
